[build]
builder = "nixpacks"

[deploy]
startCommand = "cd alma-backend && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn mysite.wsgi --bind 0.0.0.0:$PORT"

# Configuración CRUCIAL para archivos estáticos
[[static]]
dir = "alma-backend/staticfiles"