[build]
builder = "nixpacks"

[phases.build]
nixPkgs = ["postgresql"]  # Solo si usas PostgreSQL, sino quita esta línea

[phases.install]
commands = [
    "cd alma-backend",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[deploy]
startCommand = "cd alma-backend && python manage.py migrate && gunicorn mysite.wsgi --bind 0.0.0.0:$PORT"

[[static]]
dir = "alma-backend/staticfiles"