[build]
builder = "nixpacks"

[deploy]
startCommand = "cd alma-backend && pip install -r requirements.txt && python manage.py migrate && gunicorn mysite.wsgi --bind 0.0.0.0:$PORT"

[[static]]
dir = "alma-backend/staticfiles"