# Generated by Django 5.2.3 on 2025-06-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_pedido_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='subtotal',
        ),
    ]
