# Generated by Django 5.2.3 on 2025-06-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_alter_insumo_stock_actual_alter_insumo_stock_minimo_and_more'),
        ('pedidos', '0003_remove_detallepedido_precio_unitario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='ingredientes_extra',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='ingredientes_extra',
            field=models.ManyToManyField(blank=True, related_name='detalles_extra', to='insumos.insumo'),
        ),
    ]
