# Generated by Django 5.2.3 on 2025-06-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_alter_insumo_stock_actual_alter_insumo_stock_minimo_and_more'),
        ('pedidos', '0004_remove_detallepedido_ingredientes_extra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='ingredientes_extra',
        ),
        migrations.CreateModel(
            name='IngredientesExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_extra', to='pedidos.detallepedido')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.insumo')),
            ],
        ),
    ]
