# Generated by Django 5.2.3 on 2025-06-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_detallepedido_ingredientes_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(),
        ),
    ]
