# Generated by Django 5.2.3 on 2025-08-07 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0006_alter_insumo_categoria'),
        ('pedidos', '0006_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientesextra',
            name='UnidadMedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insumos.unidadmedida'),
        ),
    ]
