# Generated by Django 5.2.3 on 2025-09-09 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_ingredientesextra_unidadmedida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detallepedido_set', to='pedidos.pedido'),
        ),
    ]
