# Generated by Django 5.2.3 on 2025-09-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_detallepedido_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientesextra',
            old_name='UnidadMedida',
            new_name='unidad_medida',
        ),
    ]
