# Generated by Django 5.2.3 on 2025-09-10 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0010_remove_categoriainsumo_unidades_permitidas_and_more'),
        ('pedidos', '0010_rename_unidadmedida_ingredientesextra_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientesextra',
            name='unidad_medida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insumos.unidadmedida'),
            preserve_default=False,
        ),
    ]
