# Generated by Django 5.2.3 on 2025-11-23 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos', '0012_historialstock_es_temporal'),
        ('pedidos', '0013_alter_pedido_options_alter_pedido_fecha_pedido'),
        ('recetas', '0011_receta_veces_hecha_hoy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCierreDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('recetas_registradas', models.IntegerField(default=0)),
                ('pedidos_registrados', models.IntegerField(default=0)),
                ('insumos_registrados', models.IntegerField(default=0)),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Cierre Diario',
                'verbose_name_plural': 'Historiales de Cierres Diarios',
                'db_table': 'cierre_dia_historial',
            },
        ),
        migrations.CreateModel(
            name='HistorialInsumosUtilizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.DecimalField(decimal_places=3, max_digits=10)),
                ('motivo', models.CharField(max_length=255)),
                ('cierre_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='cierre_diario.historialcierredia')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.insumo')),
            ],
            options={
                'db_table': 'cierre_dia_insumos',
            },
        ),
        migrations.CreateModel(
            name='HistorialPedidosDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cierre_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='cierre_diario.historialcierredia')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
            options={
                'db_table': 'cierre_dia_pedidos',
            },
        ),
        migrations.CreateModel(
            name='HistorialRecetasDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_preparada', models.IntegerField(default=0)),
                ('cierre_dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='cierre_diario.historialcierredia')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.receta')),
            ],
            options={
                'db_table': 'cierre_dia_recetas',
            },
        ),
    ]
