# Generated by Django 5.2.3 on 2025-06-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='rinde',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recetainsumo',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
