# Generated by Django 5.2.3 on 2025-08-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_alter_receta_rinde_alter_recetainsumo_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='rinde',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='recetainsumo',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
