# Generated by Django 5.2.3 on 2025-08-07 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0006_alter_insumo_categoria'),
        ('recetas', '0003_alter_receta_rinde_alter_recetainsumo_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetainsumo',
            name='UnidadMedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insumos.unidadmedida'),
        ),
    ]
