# Generated by Django 5.2.3 on 2025-08-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_recetainsumo_unidadmedida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recetainsumo',
            old_name='UnidadMedida',
            new_name='unidad_medida',
        ),
    ]
