# Generated by Django 5.2.3 on 2025-08-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_rename_unidadmedida_recetainsumo_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='veces_hecha',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
