# Generated by Django 5.2.3 on 2025-08-19 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0006_alter_insumo_categoria'),
        ('recetas', '0006_receta_veces_hecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetainsumo',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recetainsumo',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.unidadmedida'),
        ),
    ]
