# Generated by Django 5.2.3 on 2025-09-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0007_alter_recetainsumo_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='unidad_rinde',
            field=models.CharField(choices=[('porciones', 'Porciones'), ('unidades', 'Unidades')], max_length=20),
        ),
    ]
