# Generated by Django 5.2.3 on 2025-09-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0008_alter_receta_unidad_rinde'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
