# Generated by Django 5.2.3 on 2025-09-29 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0009_receta_precio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receta',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='recetainsumo',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='recetas.receta'),
        ),
    ]
