# Generated by Django 5.2.3 on 2025-11-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0010_alter_receta_costo_total_alter_receta_costo_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='veces_hecha_hoy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
