# Generated by Django 5.2.3 on 2025-11-24 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0011_receta_veces_hecha_hoy'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_preparacion', models.DateTimeField(auto_now_add=True)),
                ('cantidad_preparada', models.PositiveIntegerField(default=1)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='recetas.receta')),
            ],
            options={
                'ordering': ['-fecha_preparacion'],
            },
        ),
    ]
