# Generated by Django 5.2.3 on 2025-11-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0012_historialreceta'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='ultima_actualizacion_diaria',
            field=models.DateField(auto_now=True),
        ),
    ]
