# Generated by Django 5.2.3 on 2025-12-07 04:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0013_receta_ultima_actualizacion_diaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialreceta',
            name='fecha_preparacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
