# Generated by Django 5.2.3 on 2025-12-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0014_alter_historialreceta_fecha_preparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialreceta',
            name='costo_total_historico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historialreceta',
            name='precio_venta_historico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
