# Generated by Django 5.2.3 on 2025-06-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='stock_actual',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_minimo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='tipo_insumo',
            field=models.CharField(choices=[('harina', 'Harina'), ('azucares', 'Azúcares'), ('huevos', 'Huevos'), ('grasas', 'Grasas'), ('lacteos', 'Leche y productos lácteos'), ('levaduras', 'Levaduras'), ('esencias', 'Esencias y aromas'), ('colorantes', 'Colorantes'), ('frutas', 'Frutas'), ('frutos_secos', 'Frutos secos'), ('chocolates', 'Chocolates'), ('otros', 'Otros')], max_length=50),
        ),
    ]
