# Generated by Django 5.2.3 on 2025-08-07 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0003_categoriainsumo_unidadmedida_alter_insumo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriainsumo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='categoriainsumo',
            name='icono',
        ),
    ]
