# Generated by Django 5.2.3 on 2025-08-07 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0004_remove_categoriainsumo_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriainsumo',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría de Insumo', 'verbose_name_plural': 'Categorías de Insumos'},
        ),
        migrations.RemoveField(
            model_name='categoriainsumo',
            name='orden',
        ),
    ]
