# Generated by Django 5.2.3 on 2025-08-07 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0005_alter_categoriainsumo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insumos.categoriainsumo', verbose_name='Categoria de insumo'),
        ),
    ]
