# Generated by Django 5.2.3 on 2025-08-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0006_alter_insumo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='stock_actual',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
