# Generated by Django 5.2.3 on 2025-08-26 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0007_alter_insumo_stock_actual_alter_insumo_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedida',
            name='es_unidad_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='factor_conversion_base',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='unidad_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insumos.unidadmedida'),
        ),
    ]
