# Generated by Django 5.2.3 on 2025-08-26 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0008_unidadmedida_es_unidad_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='unidadmedida',
            old_name='factor_conversion_base',
            new_name='factor_conversion',
        ),
        migrations.RemoveField(
            model_name='unidadmedida',
            name='es_unidad_base',
        ),
        migrations.AddField(
            model_name='categoriainsumo',
            name='unidades_permitidas',
            field=models.ManyToManyField(blank=True, to='insumos.tipounidad'),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='insumos.tipounidad'),
        ),
    ]
