# Generated by Django 5.2.3 on 2025-08-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0009_tipounidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriainsumo',
            name='unidades_permitidas',
        ),
        migrations.RemoveField(
            model_name='unidadmedida',
            name='tipo',
        ),
        migrations.RenameField(
            model_name='unidadmedida',
            old_name='factor_conversion',
            new_name='factor_conversion_base',
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='es_unidad_base',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TipoUnidad',
        ),
    ]
