# Generated by Django 5.2.3 on 2025-10-21 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0010_remove_categoriainsumo_unidades_permitidas_and_more'),
        ('pedidos', '0013_alter_pedido_options_alter_pedido_fecha_pedido'),
        ('recetas', '0010_alter_receta_costo_total_alter_receta_costo_unitario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('RECETA', 'Preparación de Receta'), ('INGREDIENTE_EXTRA', 'Ingrediente Extra en Pedido'), ('AJUSTE', 'Ajuste Manual'), ('COMPRA', 'Compra/Reposición')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='insumos.insumo')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pedido')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recetas.receta')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.unidadmedida')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
