# Generated by Django 5.2.3 on 2025-11-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0011_historialstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialstock',
            name='es_temporal',
            field=models.BooleanField(default=False),
        ),
    ]
