# Generated by Django 5.2.3 on 2025-11-25 14:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0012_historialstock_es_temporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialstock',
            name='tipo_movimiento',
            field=models.CharField(choices=[('RECETA', 'Preparación de Receta'), ('INGREDIENTE_EXTRA', 'Ingrediente Extra en Pedido'), ('AJUSTE', 'Ajuste Manual'), ('COMPRA', 'Compra/Reposición'), ('PERDIDA', 'Pérdida')], max_length=20),
        ),
        migrations.CreateModel(
            name='Perdida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('motivo', models.CharField(choices=[('deterioro', 'Deterioro'), ('vencimiento', 'Vencimiento'), ('rotura', 'Rotura'), ('error', 'Error en registro'), ('uso_interno', 'Uso interno'), ('otro', 'Otro')], max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perdidas', to='insumos.insumo')),
            ],
            options={
                'verbose_name': 'Pérdida de Stock',
                'verbose_name_plural': 'Pérdidas de Stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='historialstock',
            name='perdida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insumos.perdida'),
        ),
    ]
